### PR TITLE
uio: dfl: add MODULE_ALIAS for all type/id pairs

### PR DESCRIPTION
**Pull request by fpgamatt**
For the out of tree driver, one needs to add a MODULE_ALIAS for each feature type/id pair for the module to properly autoload.

### CODE REVIEW

**Review by bmuddebi — APPROVED** [review]
Looks  Good to me

**Review by rchriste1 — APPROVED** [review]
Looks fine to me.

**Comment by pcolberg** [comment]
@fpgamatt What is the reason for not including an alias for https://github.com/OFS/linux-dfl-backport/blob/0799189124eec2f9df33878e2cb641952f7bf9d9/drivers/uio/uio_dfl.c#L166

**Comment by fpgamatt** [comment]
Hi Peter,
My original reason for not including an alias for the ETH_GROUP was the mistaken belief that this feature was no in use. In hind sight, the feature is used in n3000 cards and should be included. I'll submit another patch.

Matthew

**Pull request merged**
