### PR TITLE
.github: workflows: build modules on Fedora 39 and rawhide

### PR DESCRIPTION
**Pull request by pcolberg**
Fedora ships kernels relatively close to upstream and on a frequent cadence, currently Linux 6.6 (Fedora 39) and (pre) 6.8 (rawhide).

### CODE REVIEW

**Review by fpgamatt — APPROVED** [review]
Looks good to me.

**Comment by pcolberg** [comment]
Latest force-push resolves a few off-by-one errors with regard to Linux kernel versions. A correct way to determine the tag containing a commit is, e.g.,
```
% git name-rev --tags --name-only c124fd9a969a
v5.13-rc1~54^2~38
```

**Review by michael-adler — APPROVED** [review]
Built an rpm and installed on the prebuilt 6.6.12 kernel from elrepo.

**Review by rchriste1 — COMMENTED** [review]
The changes looks fine. When doing the testing I realized that the underlying commit does not compile on CentOS 8.2 and CentOS 8.3. I have created a pull request for doing the backport: https://github.com/OFS/linux-dfl-backport/pull/107

**Comment by pcolberg** [comment]
I will merge this after https://github.com/OFS/linux-dfl-backport/pull/107 and https://github.com/OFS/linux-dfl-backport/pull/109, which will conclude the `fpga-ofs-dev-6.1-lts` branch. This PR will start the `fpga-ofs-dev-6.6-lts` branch.

**Pull request merged**
