### PR TITLE
Backport fpga-ofs-dev-6.1-lts

### PR DESCRIPTION
**Pull request by pcolberg**
Backport up to commit https://github.com/OFS/linux-dfl/commit/e3b11d27bc6cb92fe4ff2260512a38a4bfb6e4eb.

### CODE REVIEW

**Comment by pcolberg** [comment]
This still lacks the new modules, until I understand the precise ordering of the backport `Makefile`.
```diff
git diff linux-dfl-backport/intel-test/fpga-ofs-dev-6.1-lts.. drivers/fpga/{Kconfig,Makefile}

diff --git a/drivers/fpga/Kconfig b/drivers/fpga/Kconfig
index a9363944b11e..64eee24bbc91 100644
--- a/drivers/fpga/Kconfig
+++ b/drivers/fpga/Kconfig
@@ -192,6 +192,16 @@ config FPGA_DFL_AFU
 	 to the FPGA infrastructure via a Port. There may be more than one
 	 Port/AFU per DFL based FPGA device.
 
+config FPGA_DFL_PRIV_FEAT
+	tristate "FPGA DFL PRIV FEAT Driver"
+	depends on FPGA_DFL
+	help
+	 This is the driver for FPGA Private Features which will implement
+	 FIU feature start.
+
+	 To compile this driver as a module, choose M here: the module will
+	 be called dfl_priv_feat.
+
 config FPGA_DFL_NIOS_INTEL_PAC_N3000
 	tristate "FPGA DFL NIOS Driver for Intel PAC N3000"
 	depends on FPGA_DFL
@@ -218,6 +228,25 @@ config FPGA_DFL_PCI
 
 	 To compile this as a module, choose M here.
 
+config FPGA_DFL_PCI_SVA
+	tristate "FPGA DFL PCIe Shared Virtual Addressing Device Driver"
+	depends on PCI && FPGA_DFL && IOMMU_SVA
+	help
+	 Select this option to enable PASID and IOMMU binding of DFL-based
+	 devices that support shared virtual memory.
+
+config FPGA_DFL_PLATFORM
+	tristate "FPGA DFL Platform Driver"
+	depends on FPGA_DFL
+	depends on OF || COMPILE_TEST
+	help
+	 Select this option to enable the Device Feature List (DFL) platform driver.
+	 For more detailed information about DFL, please refer to the Linux DFL
+	 documentation available at: <https://docs.kernel.org/fpga/dfl.html>.
+
+	 To compile this driver as a module, choose M here: the module will be
+	 called dfl_platform.
+
 config FPGA_DFL_HSSI
 	tristate "FPGA DFL HSSI Driver"
 	depends on FPGA_DFL
@@ -255,4 +284,11 @@ config FPGA_M10_BMC_SEC_UPDATE
 	 (BMC) and provides support for secure updates for the BMC image,
 	 the FPGA image, the Root Entry Hashes, etc.
 
+config FPGA_DFL_CXL_CACHE
+	tristate "Intel CXL cache driver"
+	depends on FPGA_DFL
+	help
+	 This is the driver for CXL cache Accelerated Function Unit
+	 (AFU) which provides interfaces to MMIO region and dma buffers.
+
 endif # FPGA
diff --git a/drivers/fpga/Makefile b/drivers/fpga/Makefile
index ae3cc9913e42..027c651cbc75 100644
--- a/drivers/fpga/Makefile
+++ b/drivers/fpga/Makefile
@@ -40,6 +40,7 @@ obj-$(CONFIG_OF_FPGA_REGION)		+= of-fpga-region.o
 # FPGA Device Feature List Support
 obj-$(CONFIG_FPGA_DFL)			+= dfl.o
 obj-$(CONFIG_FPGA_DFL_FME)		+= dfl-fme.o
+obj-$(CONFIG_FPGA_DFL_PRIV_FEAT)	+= dfl-priv-feat.o
 obj-$(CONFIG_FPGA_DFL_FME_MGR)		+= dfl-fme-mgr.o
 obj-$(CONFIG_FPGA_DFL_FME_BRIDGE)	+= dfl-fme-br.o
 obj-$(CONFIG_FPGA_DFL_FME_REGION)	+= dfl-fme-region.o
@@ -50,8 +51,13 @@ dfl-fme-objs += dfl-fme-perf.o
 dfl-afu-objs := dfl-afu-main.o dfl-afu-region.o dfl-afu-dma-region.o
 dfl-afu-objs += dfl-afu-error.o
 
+dfl-priv-feat-objs :=  dfl-priv-feat-main.o
+
 obj-$(CONFIG_FPGA_DFL_NIOS_INTEL_PAC_N3000)	+= dfl-n3000-nios.o
 
 # Drivers for FPGAs which implement DFL
 obj-$(CONFIG_FPGA_DFL_PCI)		+= dfl-pci.o
+obj-$(CONFIG_FPGA_DFL_PCI_SVA)		+= dfl-pci-sva.o
+obj-$(CONFIG_FPGA_DFL_PLATFORM)		+= dfl-platform.o
 obj-$(CONFIG_FPGA_DFL_HSSI)		+= dfl-hssi.o
+obj-$(CONFIG_FPGA_DFL_CXL_CACHE)	+= dfl-cxl-cache.o
```

**Review by fpgamatt — COMMENTED** [review]
How did you figure out which RHEL revision?

Do we want this in the intel-test/fpga-ofs-dev-6.1-lts or just the intel/fpga-ofs-dev-6.1-lts? At the moment I think they are the same.

**Comment by pcolberg** [comment]
> How did you figure out which RHEL revision?

I started from a third-party vendor's [Supported Red Hat Enterprise Linux kernel versions](https://kcm.trellix.com/corporate/index?page=content&id=KB93176) to get a basic idea of the RHEL kernel major versions versus releases, then downloaded all `RHEL-*/BaseOS/source/tree/Packages/kernel-*.src.rpm` and compared `rg iommu_sva_bind_device */include/linux/iommu.h`.

> Do we want this in the intel-test/fpga-ofs-dev-6.1-lts or just the intel/fpga-ofs-dev-6.1-lts? At the moment I think they are the same.

Only `intel-test` for now. When I submitted https://github.com/OFS/linux-dfl-backport/pull/90 and https://github.com/OFS/linux-dfl-backport/pull/92, I had missed that the established workflow is PR → `intel-test/` → verification testing → `intel/`.

**Comment by pcolberg** [comment]
Moving back to draft. [`IOMMU_DEV_FEAT_IOPF` is required for `dfl-pci-sva`](https://github.com/OFS/linux-dfl-backport/actions/runs/7136018666/job/19433808000) but was only introduced as late as RHEL 8.6 (4.18.0-372).

**Comment by pcolberg** [comment]
I hoped that f0c11954342ea5a87f35632a702b58dfdc64c6d4 is sufficient to disable the dfl-pci-sva driver when `CONFIG_IOMMU_SVA` is absent, but it [does not work for the backport Makefile](https://github.com/OFS/linux-dfl-backport/actions/runs/7173985421/job/19534522901):
```
# grep CONFIG_IOMMU_SVA /lib/modules/5.4.0-169-generic/build/.config   
# 
```
```
2023-12-11T22:11:31.0855352Z   CC [M]  /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.o
2023-12-11T22:11:31.2906200Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.c: In function 'ioctl_sva_bind_dev':
2023-12-11T22:11:31.2908595Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.c:181:21: error: 'struct mm_struct' has no member named 'pasid'
2023-12-11T22:11:31.2910357Z   181 |   return current->mm->pasid;
2023-12-11T22:11:31.2911446Z       |                     ^~
2023-12-11T22:11:31.2912824Z In file included from /__w/linux-dfl-backport/linux-dfl-backport/include/linux/device.h:7,
2023-12-11T22:11:31.2914110Z                  from ./include/linux/iommu.h:11,
2023-12-11T22:11:31.2915664Z                  from /__w/linux-dfl-backport/linux-dfl-backport/include/linux/iommu.h:13,
2023-12-11T22:11:31.2917201Z                  from /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.c:27:
2023-12-11T22:11:31.2919324Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.c:186:23: error: 'struct mm_struct' has no member named 'pasid'
2023-12-11T22:11:31.2921212Z   186 |    handle, current->mm->pasid);
2023-12-11T22:11:31.2921969Z       |                       ^~
2023-12-11T22:11:31.2923024Z ./include/linux/device.h:1808:33: note: in definition of macro 'dev_info'
2023-12-11T22:11:31.2924394Z  1808 |  _dev_info(dev, dev_fmt(fmt), ##__VA_ARGS__)
2023-12-11T22:11:31.2925280Z       |                                 ^~~~~~~~~~~
2023-12-11T22:11:31.2926889Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.c:184:2: note: in expansion of macro 'pci_info'
2023-12-11T22:11:31.2928703Z   184 |  pci_info(dev->pdev, "%s: pid %d, bind sva_handle %p, pasid = %d\n",
2023-12-11T22:11:31.2929568Z       |  ^~~~~~~~
2023-12-11T22:11:31.2930876Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.c:194:20: error: 'struct mm_struct' has no member named 'pasid'
2023-12-11T22:11:31.2932410Z   194 |  return current->mm->pasid;
2023-12-11T22:11:31.2933023Z       |                    ^~
2023-12-11T22:11:31.2984937Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.c:195:1: error: control reaches end of non-void function [-Werror=return-type]
2023-12-11T22:11:31.2986776Z   195 | }
2023-12-11T22:11:31.2987286Z       | ^
2023-12-11T22:11:31.3001624Z cc1: some warnings being treated as errors
2023-12-11T22:11:31.3043992Z make[2]: *** [scripts/Makefile.build:270: /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-pci-sva.o] Error 1
2023-12-11T22:11:31.3047267Z make[1]: *** [Makefile:1778: /__w/linux-dfl-backport/linux-dfl-backport] Error 2
2023-12-11T22:11:31.3048587Z make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-169-generic'
```

**Review by fpgamatt — APPROVED** [review]

**Comment by fpgamatt** [comment]
It looks like I accidently approved this PR, and according to Peter's comment, it looks like we need to properly use the .config of the running kernel to learn what is configured or not.

**Comment by pcolberg** [comment]
> It looks like I accidently approved this PR, and according to Peter's comment, it looks like we need to properly use the .config of the running kernel to learn what is configured or not.

Thanks @fpgamatt; no worries, I will address that issue before merging. I assumed that the kernel makefiles consider dependencies defined in `Kconfig` files even for external modules, but that is not the case.

**Comment by pcolberg** [comment]
Another [build failure on Ubuntu 20.04 LTS](https://github.com/OFS/linux-dfl-backport/actions/runs/7174582334/job/19536291694), which was previously addressed for a different module in commit e428f7777e3ac4a04e917c431b05de07b82092b8 ("fpga: dfl-afu-dma-region: soft revert pin_user_pages").
https://github.com/OFS/linux-dfl-backport/blob/dbfb71025e1f6e1f225e7cc07e1a4c0c916ea862/drivers/fpga/dfl-afu-dma-region.c#L21-L35
```
2023-12-11T23:17:15.2592810Z   CC [M]  /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-cxl-cache.o
2023-12-11T23:17:15.4547422Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-cxl-cache.c: In function 'cxl_cache_unpin_pages':
2023-12-11T23:17:15.4550608Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-cxl-cache.c:109:2: error: implicit declaration of function 'unpin_user_pages'; did you mean 'unpin_user_page'? [-Werror=implicit-function-declaration]
2023-12-11T23:17:15.4552851Z   109 |  unpin_user_pages(*pages, npages);
2023-12-11T23:17:15.4553542Z       |  ^~~~~~~~~~~~~~~~
2023-12-11T23:17:15.4554203Z       |  unpin_user_page
2023-12-11T23:17:15.4610367Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-cxl-cache.c: In function 'cxl_cache_dma_pin_pages':
2023-12-11T23:17:15.4613504Z /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-cxl-cache.c:153:11: error: implicit declaration of function 'pin_user_pages_fast'; did you mean 'get_user_pages_fast'? [-Werror=implicit-function-declaration]
2023-12-11T23:17:15.4616324Z   153 |  pinned = pin_user_pages_fast(region->user_addr, npages, flags, region->pages);
2023-12-11T23:17:15.4617432Z       |           ^~~~~~~~~~~~~~~~~~~
2023-12-11T23:17:15.5603900Z       |           get_user_pages_fast
2023-12-11T23:17:15.5604693Z cc1: some warnings being treated as errors
2023-12-11T23:17:15.5647557Z make[2]: *** [scripts/Makefile.build:270: /__w/linux-dfl-backport/linux-dfl-backport/drivers/fpga/dfl-cxl-cache.o] Error 1
2023-12-11T23:17:15.5654361Z make[1]: *** [Makefile:1778: /__w/linux-dfl-backport/linux-dfl-backport] Error 2
2023-12-11T23:17:15.5655672Z make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-169-generic'
2023-12-11T23:17:15.5657197Z make: *** [Makefile:163: all] Error 2
```

**Comment by pcolberg** [comment]
@fpgamatt Re-requesting review since I am not sure whether the pinning behaviour of `get_user_pages()` is an adequate substitute for the explicit pinning of `pin_user_pages()` in commit 8a46b94a62927c5141d478e1823d8fca74915098 on older kernels.

**Comment by pcolberg** [comment]
[Explicit pinning of user-space pages](https://lwn.net/Articles/807108/) provides background on `get_user_pages*()` versus `pin_user_pages*()`. Older kernels provide [`put_user_pages()`](https://elixir.bootlin.com/linux/v5.5.19/source/mm/gup.c#L120), which is almost identical to the custom [`put_all_pages()`](https://github.com/OFS/linux-dfl-backport/blob/dbfb71025e1f6e1f225e7cc07e1a4c0c916ea862/drivers/fpga/dfl-afu-dma-region.c#L26-L33) except for the null page check.

**Review by fpgamatt — APPROVED** [review]

**Pull request merged**
